name = "EventIntervals"
uuid = "1751c77c-d90c-5130-9faa-3b4ea8d90a70"
version = "0.1.7"
authors = ["Galen Lynch <galen@galenlynch.com>"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SignalIndices = "18f53e89-494d-4131-905c-653e8ada6cd8"
SortedIntervals = "b6c59e15-8662-4f8a-b157-cd910e143dcd"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataStructures = "0.15 - 0.19"
SignalIndices = "0.1.1"
SortedIntervals = "0.1.2"
julia = "1.6"
