name = "PointProcesses"
uuid = "1751c77c-d90c-5130-9faa-3b4ea8d90a70"
authors = ["Galen Lynch <galen.lynch@gmail.com>"]
version = "0.1.2"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GLUtilities = "8b4c6747-1f02-570a-a961-a96037df41d6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Compat = "1 - 3"
GLUtilities = "0.0.5 - 0.2"
julia = "0.6 - 1"
DataStructures = "0.15 - 0.18"
