name = "PointProcesses"
uuid = "1751c77c-d90c-5130-9faa-3b4ea8d90a70"
version = "0.1.3"
authors = ["Galen Lynch <galen@galenlynch.com>"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GLUtilities = "8b4c6747-1f02-570a-a961-a96037df41d6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataStructures = "0.15 - 0.18"
GLUtilities = "0.0.5 - 0.2"
julia = "1.6"
